#!/bin/bash
# ACG-Faka GHCR deployment script.
# Run on the production host after GitHub Actions publishes the image:
#   nohup bash /opt/acgfaka/repo/deploy/update.sh &

set -euo pipefail

BASE_DIR="${BASE_DIR:-/opt/acgfaka}"
REPO_DIR="${REPO_DIR:-${BASE_DIR}/repo}"
COMPOSE_FILE="${COMPOSE_FILE:-${REPO_DIR}/docker-compose.prod.yml}"
COMPOSE_OVERRIDE_FILE="${COMPOSE_OVERRIDE_FILE:-${BASE_DIR}/docker-compose.override.yml}"
DEFAULT_ENV_FILE="${BASE_DIR}/.env.prod"
LEGACY_ENV_FILE="${BASE_DIR}.env.prod"
if [ -z "${ENV_FILE:-}" ]; then
    if [ -f "$DEFAULT_ENV_FILE" ]; then
        ENV_FILE="$DEFAULT_ENV_FILE"
    elif [ -f "$LEGACY_ENV_FILE" ]; then
        ENV_FILE="$LEGACY_ENV_FILE"
    else
        ENV_FILE="$DEFAULT_ENV_FILE"
    fi
fi
PROJECT_NAME="${PROJECT_NAME:-acgfaka}"
DEFAULT_IMAGE_NAME="ghcr.io/541968679/acg-faka:latest"
PREV_TAG="${PREV_TAG:-acgfaka-custom:prev}"
BRANCH="${BRANCH:-main}"

HEALTH_RETRIES="${HEALTH_RETRIES:-6}"
HEALTH_INTERVAL="${HEALTH_INTERVAL:-5}"
LOG_FILE="${LOG_FILE:-${BASE_DIR}/deploy.log}"

env_file_value() {
    local key=$1
    if [ ! -f "$ENV_FILE" ]; then
        return 0
    fi

    awk -F= -v key="$key" '
        $0 ~ "^[[:space:]]*#" { next }
        $1 == key {
            sub(/^[^=]*=/, "")
            gsub(/\r$/, "")
            gsub(/^["'\'']|["'\'']$/, "")
            print
            exit
        }
    ' "$ENV_FILE"
}

IMAGE_NAME="${ACGFAKA_IMAGE:-$(env_file_value ACGFAKA_IMAGE)}"
IMAGE_NAME="${IMAGE_NAME:-$DEFAULT_IMAGE_NAME}"

log() {
    mkdir -p "$(dirname "$LOG_FILE")"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

compose() {
    docker compose \
        -p "$PROJECT_NAME" \
        -f "$COMPOSE_FILE" \
        -f "$COMPOSE_OVERRIDE_FILE" \
        --env-file "$ENV_FILE" \
        "$@"
}

health_check() {
    local retries=$1
    local interval=$2

    for i in $(seq 1 "$retries"); do
        if compose exec -T app php -r '$body = @file_get_contents("http://127.0.0.1/install/rewrite"); exit(str_contains((string)$body, "success") ? 0 : 1);'; then
            log "Health check passed (attempt $i/$retries)"
            return 0
        fi
        log "Health check attempt $i/$retries failed, waiting ${interval}s..."
        sleep "$interval"
    done

    return 1
}

ensure_compose_uses_release_image() {
    log "--- Ensuring compose uses ${IMAGE_NAME} ---"
    mkdir -p "$BASE_DIR"

    if [ -f "$COMPOSE_OVERRIDE_FILE" ]; then
        if ! grep -Eq "Generated by deploy/update.sh|acgfaka-custom:latest|ghcr.io/.*/acg-faka" "$COMPOSE_OVERRIDE_FILE"; then
            log "ERROR: Refusing to overwrite unrecognized compose override: $COMPOSE_OVERRIDE_FILE"
            return 1
        fi
    fi

    cat > "$COMPOSE_OVERRIDE_FILE" <<EOF
# Generated by deploy/update.sh.
# Keeps production on the GitHub Actions built image.
services:
  app:
    image: ${IMAGE_NAME}
  cron:
    image: ${IMAGE_NAME}
EOF

    local app_image cron_image
    app_image="$(compose config | awk '
        $1 == "app:" { in_service=1; next }
        in_service && /^[[:space:]]{2}[A-Za-z0-9_-]+:/ { exit }
        in_service && $1 == "image:" { print $2; exit }
    ')"
    cron_image="$(compose config | awk '
        $1 == "cron:" { in_service=1; next }
        in_service && /^[[:space:]]{2}[A-Za-z0-9_-]+:/ { exit }
        in_service && $1 == "image:" { print $2; exit }
    ')"

    if [ "$app_image" != "$IMAGE_NAME" ] || [ "$cron_image" != "$IMAGE_NAME" ]; then
        log "ERROR: Compose images resolved to app=${app_image}, cron=${cron_image}; expected ${IMAGE_NAME}"
        return 1
    fi
}

pull_release_image() {
    log "--- Pulling release image ${IMAGE_NAME} ---"
    docker pull "$IMAGE_NAME" 2>&1 | tee -a "$LOG_FILE"
}

restart_stack() {
    log "--- Restarting ACG-Faka stack ---"
    compose up -d --force-recreate app cron caddy 2>&1 | tee -a "$LOG_FILE"
}

run_db_migrations() {
    log "--- Running database migrations ---"
    compose exec -T db sh -s <<'SH' 2>&1 | tee -a "$LOG_FILE"
set -e
prefix="${DB_PREFIX:-acg_}"

mysql -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" "$MYSQL_DATABASE" <<SQL
CREATE TABLE IF NOT EXISTS \`${prefix}json_pickup\` (
  \`id\` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'primary key',
  \`code\` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'pickup code',
  \`commodity_id\` int unsigned NOT NULL COMMENT 'commodity id',
  \`card_id\` int unsigned DEFAULT NULL COMMENT 'linked card id',
  \`order_id\` int unsigned DEFAULT NULL COMMENT 'first download order id',
  \`batch_no\` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'import batch',
  \`source_filename\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'source filename',
  \`filename\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'download filename',
  \`content\` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'json content',
  \`content_hash\` char(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'sha256 hash',
  \`size\` int unsigned NOT NULL DEFAULT 0 COMMENT 'content bytes',
  \`status\` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '0=available,1=downloaded,2=locked',
  \`max_downloads\` int unsigned NOT NULL DEFAULT 1 COMMENT 'max downloads',
  \`download_count\` int unsigned NOT NULL DEFAULT 0 COMMENT 'download count',
  \`expire_time\` datetime DEFAULT NULL COMMENT 'expire time',
  \`create_time\` datetime NOT NULL COMMENT 'create time',
  \`update_time\` datetime NOT NULL COMMENT 'update time',
  \`last_download_time\` datetime DEFAULT NULL COMMENT 'last download time',
  PRIMARY KEY (\`id\`) USING BTREE,
  UNIQUE KEY \`code\` (\`code\`) USING BTREE,
  KEY \`commodity_id\` (\`commodity_id\`) USING BTREE,
  KEY \`card_id\` (\`card_id\`) USING BTREE,
  KEY \`order_id\` (\`order_id\`) USING BTREE,
  KEY \`batch_no\` (\`batch_no\`) USING BTREE,
  KEY \`status\` (\`status\`) USING BTREE,
  KEY \`expire_time\` (\`expire_time\`) USING BTREE,
  CONSTRAINT \`${prefix}json_pickup_ibfk_1\` FOREIGN KEY (\`commodity_id\`) REFERENCES \`${prefix}commodity\` (\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT \`${prefix}json_pickup_ibfk_2\` FOREIGN KEY (\`card_id\`) REFERENCES \`${prefix}card\` (\`id\`) ON DELETE SET NULL ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;

UPDATE \`${prefix}pay\`
SET \`commodity\` = 0, \`recharge\` = 0
WHERE \`code\` = 'alipay' AND \`handle\` = 'Epay';
SQL
SH
}

verify_running_image() {
    local expected_id app_id app_name app_status cron_id cron_name cron_status revision
    expected_id="$(docker image inspect "$IMAGE_NAME" --format '{{.Id}}')"
    revision="$(docker image inspect "$IMAGE_NAME" --format '{{ index .Config.Labels "org.opencontainers.image.revision" }}' 2>/dev/null || true)"

    app_id="$(docker inspect acgfaka-app --format '{{.Image}}')"
    app_name="$(docker inspect acgfaka-app --format '{{.Config.Image}}')"
    app_status="$(docker inspect acgfaka-app --format '{{.State.Status}}')"
    cron_id="$(docker inspect acgfaka-cron --format '{{.Image}}')"
    cron_name="$(docker inspect acgfaka-cron --format '{{.Config.Image}}')"
    cron_status="$(docker inspect acgfaka-cron --format '{{.State.Status}}')"

    if [ "$app_name" != "$IMAGE_NAME" ] || [ "$app_id" != "$expected_id" ]; then
        log "ERROR: app image is ${app_name} (${app_id}), expected ${IMAGE_NAME} (${expected_id})"
        return 1
    fi

    if [ "$app_status" != "running" ]; then
        log "ERROR: app container status is ${app_status}; expected running"
        return 1
    fi

    if [ "$cron_name" != "$IMAGE_NAME" ] || [ "$cron_id" != "$expected_id" ]; then
        log "ERROR: cron image is ${cron_name} (${cron_id}), expected ${IMAGE_NAME} (${expected_id})"
        return 1
    fi

    if [ "$cron_status" != "running" ]; then
        log "ERROR: cron container status is ${cron_status}; expected running"
        return 1
    fi

    log "Running image verified: ${IMAGE_NAME} (${expected_id}), revision=${revision:-unknown}"
}

cleanup_docker_disk() {
    log "--- Docker disk cleanup ---"
    docker image prune -f 2>&1 | tee -a "$LOG_FILE" || \
        log "WARN: docker image prune failed"
    docker system df 2>&1 | tee -a "$LOG_FILE" || \
        log "WARN: docker system df failed"
}

do_rollback() {
    log "=== ROLLBACK: Restoring previous image ==="

    if ! docker image inspect "$PREV_TAG" >/dev/null 2>&1; then
        log "ERROR: No previous image (${PREV_TAG}) found"
        return 1
    fi

    docker tag "$PREV_TAG" "$IMAGE_NAME"
    ensure_compose_uses_release_image
    restart_stack

    sleep 8
    if health_check 3 "$HEALTH_INTERVAL" && verify_running_image; then
        log "=== ROLLBACK SUCCESSFUL ==="
        compose ps
        return 0
    fi

    log "=== ROLLBACK HEALTH CHECK FAILED: manual intervention required ==="
    return 1
}

do_deploy() {
    log "=============================================="
    log "=== Starting ACG-Faka GHCR deployment ==="
    log "=============================================="

    if [ ! -f "$ENV_FILE" ]; then
        log "ERROR: Missing env file: $ENV_FILE"
        return 1
    fi

    cd "$REPO_DIR"

    log "--- Pulling latest deploy files from origin/${BRANCH} ---"
    git fetch origin "$BRANCH" 2>&1 | tee -a "$LOG_FILE"
    git checkout "$BRANCH" 2>&1 | tee -a "$LOG_FILE"
    git pull --ff-only origin "$BRANCH" 2>&1 | tee -a "$LOG_FILE"

    ensure_compose_uses_release_image

    if docker image inspect "$IMAGE_NAME" >/dev/null 2>&1; then
        log "--- Saving current image as prev ---"
        docker tag "$IMAGE_NAME" "$PREV_TAG"
    fi

    pull_release_image

    log "--- Starting dependencies ---"
    compose up -d db redis 2>&1 | tee -a "$LOG_FILE"

    run_db_migrations

    restart_stack

    log "--- Health check (${HEALTH_RETRIES} attempts, ${HEALTH_INTERVAL}s interval) ---"
    sleep 8
    if health_check "$HEALTH_RETRIES" "$HEALTH_INTERVAL" && verify_running_image; then
        log "=== Deployment successful ==="
        compose ps
        cleanup_docker_disk
    else
        log "ERROR: Health check failed after deploy"
        do_rollback
        return 1
    fi

    log "=============================================="
    log "=== Done ==="
    log "=============================================="
}

case "${1:-deploy}" in
    deploy)
        do_deploy
        ;;
    --rollback|rollback)
        do_rollback
        ;;
    *)
        log "ERROR: Unknown argument: $1"
        exit 2
        ;;
esac
