#!/bin/bash
# ACG-Faka server-side deployment script.
# Run on the production host after pushing code to the fork:
#   nohup bash /opt/acgfaka/repo/deploy/update.sh &

set -euo pipefail

BASE_DIR="${BASE_DIR:-/opt/acgfaka}"
REPO_DIR="${REPO_DIR:-${BASE_DIR}/repo}"
COMPOSE_FILE="${COMPOSE_FILE:-${REPO_DIR}/docker-compose.prod.yml}"
COMPOSE_OVERRIDE_FILE="${COMPOSE_OVERRIDE_FILE:-${BASE_DIR}/docker-compose.override.yml}"
ENV_FILE="${ENV_FILE:-${BASE_DIR}/.env.prod}"
PROJECT_NAME="${PROJECT_NAME:-acgfaka}"

IMAGE_NAME="${IMAGE_NAME:-acgfaka-custom}"
STAGING_TAG="${IMAGE_NAME}:staging"
LATEST_TAG="${IMAGE_NAME}:latest"
PREV_TAG="${IMAGE_NAME}:prev"
BRANCH="${BRANCH:-main}"

HEALTH_RETRIES="${HEALTH_RETRIES:-6}"
HEALTH_INTERVAL="${HEALTH_INTERVAL:-5}"
LOG_FILE="${LOG_FILE:-${BASE_DIR}/deploy.log}"
DOCKER_BUILD_CACHE_MAX_AGE="${DOCKER_BUILD_CACHE_MAX_AGE:-24h}"

log() {
    mkdir -p "$(dirname "$LOG_FILE")"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

compose() {
    docker compose \
        -p "$PROJECT_NAME" \
        -f "$COMPOSE_FILE" \
        -f "$COMPOSE_OVERRIDE_FILE" \
        --env-file "$ENV_FILE" \
        "$@"
}

health_check() {
    local retries=$1
    local interval=$2

    for i in $(seq 1 "$retries"); do
        if compose exec -T app php -r '$body = @file_get_contents("http://127.0.0.1/install/rewrite"); exit(str_contains((string)$body, "success") ? 0 : 1);'; then
            log "Health check passed (attempt $i/$retries)"
            return 0
        fi
        log "Health check attempt $i/$retries failed, waiting ${interval}s..."
        sleep "$interval"
    done

    return 1
}

ensure_compose_uses_built_image() {
    log "--- Ensuring compose uses ${LATEST_TAG} ---"
    mkdir -p "$BASE_DIR"

    if [ -f "$COMPOSE_OVERRIDE_FILE" ]; then
        if ! grep -Eq "Generated by deploy/update.sh|acgfaka-custom:latest" "$COMPOSE_OVERRIDE_FILE"; then
            log "ERROR: Refusing to overwrite unrecognized compose override: $COMPOSE_OVERRIDE_FILE"
            return 1
        fi
    fi

    cat > "$COMPOSE_OVERRIDE_FILE" <<EOF
# Generated by deploy/update.sh.
# Keeps production on the image built by this host.
services:
  app:
    image: ${LATEST_TAG}
  cron:
    image: ${LATEST_TAG}
EOF

    local app_image cron_image
    app_image="$(compose config | awk '
        $1 == "app:" { in_service=1; next }
        in_service && /^[[:space:]]{2}[A-Za-z0-9_-]+:/ { exit }
        in_service && $1 == "image:" { print $2; exit }
    ')"
    cron_image="$(compose config | awk '
        $1 == "cron:" { in_service=1; next }
        in_service && /^[[:space:]]{2}[A-Za-z0-9_-]+:/ { exit }
        in_service && $1 == "image:" { print $2; exit }
    ')"

    if [ "$app_image" != "$LATEST_TAG" ] || [ "$cron_image" != "$LATEST_TAG" ]; then
        log "ERROR: Compose images resolved to app=${app_image}, cron=${cron_image}; expected ${LATEST_TAG}"
        return 1
    fi
}

restart_stack() {
    log "--- Restarting ACG-Faka stack ---"
    compose up -d --force-recreate app cron caddy 2>&1 | tee -a "$LOG_FILE"
}

verify_running_image() {
    local expected_id app_id app_name cron_id cron_name
    expected_id="$(docker image inspect "$LATEST_TAG" --format '{{.Id}}')"

    app_id="$(docker inspect acgfaka-app --format '{{.Image}}')"
    app_name="$(docker inspect acgfaka-app --format '{{.Config.Image}}')"
    cron_id="$(docker inspect acgfaka-cron --format '{{.Image}}')"
    cron_name="$(docker inspect acgfaka-cron --format '{{.Config.Image}}')"

    if [ "$app_name" != "$LATEST_TAG" ] || [ "$app_id" != "$expected_id" ]; then
        log "ERROR: app image is ${app_name} (${app_id}), expected ${LATEST_TAG} (${expected_id})"
        return 1
    fi

    if [ "$cron_name" != "$LATEST_TAG" ] || [ "$cron_id" != "$expected_id" ]; then
        log "ERROR: cron image is ${cron_name} (${cron_id}), expected ${LATEST_TAG} (${expected_id})"
        return 1
    fi

    log "Running image verified: ${LATEST_TAG} (${expected_id})"
}

cleanup_docker_disk() {
    log "--- Docker disk cleanup ---"
    docker builder prune -af --filter "until=${DOCKER_BUILD_CACHE_MAX_AGE}" 2>&1 | tee -a "$LOG_FILE" || \
        log "WARN: docker builder prune failed"
    docker image prune -f 2>&1 | tee -a "$LOG_FILE" || \
        log "WARN: docker image prune failed"
    docker system df 2>&1 | tee -a "$LOG_FILE" || \
        log "WARN: docker system df failed"
}

do_rollback() {
    log "=== ROLLBACK: Restoring previous image ==="

    if ! docker image inspect "$PREV_TAG" >/dev/null 2>&1; then
        log "ERROR: No previous image (${PREV_TAG}) found"
        return 1
    fi

    docker tag "$PREV_TAG" "$LATEST_TAG"
    ensure_compose_uses_built_image
    restart_stack

    sleep 8
    if health_check 3 "$HEALTH_INTERVAL" && verify_running_image; then
        log "=== ROLLBACK SUCCESSFUL ==="
        compose ps
        return 0
    fi

    log "=== ROLLBACK HEALTH CHECK FAILED: manual intervention required ==="
    return 1
}

do_deploy() {
    log "=============================================="
    log "=== Starting ACG-Faka deployment ==="
    log "=============================================="

    if [ ! -f "$ENV_FILE" ]; then
        log "ERROR: Missing env file: $ENV_FILE"
        return 1
    fi

    cd "$REPO_DIR"

    log "--- Pulling latest code from origin/${BRANCH} ---"
    git fetch origin "$BRANCH" 2>&1 | tee -a "$LOG_FILE"
    git checkout "$BRANCH" 2>&1 | tee -a "$LOG_FILE"
    git pull --ff-only origin "$BRANCH" 2>&1 | tee -a "$LOG_FILE"

    log "--- Building staging image on host ---"
    if ! docker build --no-cache -t "$STAGING_TAG" -f "$REPO_DIR/Dockerfile" "$REPO_DIR" 2>&1 | tee -a "$LOG_FILE"; then
        log "ERROR: Build failed. Production is still running the old image."
        return 1
    fi

    if docker image inspect "$LATEST_TAG" >/dev/null 2>&1; then
        log "--- Saving current image as prev ---"
        docker tag "$LATEST_TAG" "$PREV_TAG"
    fi

    log "--- Promoting staging to latest ---"
    docker tag "$STAGING_TAG" "$LATEST_TAG"

    ensure_compose_uses_built_image

    log "--- Starting dependencies ---"
    compose up -d db redis 2>&1 | tee -a "$LOG_FILE"

    restart_stack

    log "--- Health check (${HEALTH_RETRIES} attempts, ${HEALTH_INTERVAL}s interval) ---"
    sleep 8
    if health_check "$HEALTH_RETRIES" "$HEALTH_INTERVAL" && verify_running_image; then
        log "=== Deployment successful ==="
        compose ps
        docker rmi "$STAGING_TAG" 2>/dev/null || true
        cleanup_docker_disk
    else
        log "ERROR: Health check failed after deploy"
        do_rollback
        return 1
    fi

    log "=============================================="
    log "=== Done ==="
    log "=============================================="
}

case "${1:-deploy}" in
    deploy)
        do_deploy
        ;;
    --rollback|rollback)
        do_rollback
        ;;
    *)
        log "ERROR: Unknown argument: $1"
        exit 2
        ;;
esac
